from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


def create_report_pdf(filepath, result, complaint):
    doc = SimpleDocTemplate(filepath)

    styles = getSampleStyleSheet()

    content = []

    content.append(Paragraph("CCIA AI Investigation Report", styles['Title']))
    content.append(Spacer(1, 12))

    content.append(Paragraph("<b>Complaint</b>", styles['Heading2']))
    content.append(Paragraph(complaint, styles['BodyText']))
    content.append(Spacer(1, 12))

    content.append(Paragraph("<b>Category</b>", styles['Heading2']))
    content.append(Paragraph(result["crime_category"], styles['BodyText']))

    content.append(Paragraph("<b>Risk Level</b>", styles['Heading2']))
    content.append(
        Paragraph(
            f'{result["risk_level"]} ({result["risk_reason"]})',
            styles['BodyText']
        )
    )

    content.append(Paragraph("<b>Case Summary</b>", styles['Heading2']))
    content.append(
        Paragraph(result["case_summary"], styles['BodyText'])
    )

    content.append(Paragraph("<b>Legal Sections</b>", styles['Heading2']))
    content.append(
        Paragraph(result["legal_sections"], styles['BodyText'])
    )

    content.append(Paragraph("<b>Priority Action</b>", styles['Heading2']))
    content.append(
        Paragraph(result["priority_action"], styles['BodyText'])
    )

    content.append(Spacer(1, 12))

    content.append(
        Paragraph(
            "Generated by CCIA AI",
            styles['Italic']
        )
    )

    doc.build(content)