from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import json

def create_report_pdf(filepath, result, complaint_text):
    """
    Generate a professional PDF report for a cyber complaint.
    """
    doc = SimpleDocTemplate(filepath, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=colors.HexColor('#00308f'),
        spaceAfter=12
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=colors.HexColor('#c8a000'),
        spaceAfter=6,
        spaceBefore=12
    )
    body_style = styles['BodyText']
    body_style.fontSize = 10
    body_style.leading = 14
    
    elements = []
    
    # Title
    elements.append(Paragraph("CCIA - Cyber Crime Investigation Report", title_style))
    elements.append(Spacer(1, 0.1*inch))
    
    # Case ID & Risk
    elements.append(Paragraph(f"<b>Case ID:</b> {result.get('complaint_id', 'N/A')}", body_style))
    elements.append(Paragraph(f"<b>Risk Level:</b> {result.get('risk_level', 'N/A')}", body_style))
    elements.append(Paragraph(f"<b>Category:</b> {result.get('crime_category', 'N/A')}", body_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Summary
    elements.append(Paragraph("Case Summary", heading_style))
    elements.append(Paragraph(result.get('case_summary', 'No summary available'), body_style))
    elements.append(Spacer(1, 0.1*inch))
    
    # Priority Action
    if result.get('priority_action'):
        elements.append(Paragraph("Priority Action", heading_style))
        elements.append(Paragraph(result['priority_action'], body_style))
        elements.append(Spacer(1, 0.1*inch))
    
    # Key Indicators (AI)
    if result.get('key_indicators'):
        elements.append(Paragraph("Key Indicators (AI)", heading_style))
        for item in result['key_indicators']:
            elements.append(Paragraph(f"• {item}", body_style))
        elements.append(Spacer(1, 0.1*inch))
    
    # Investigation Steps
    if result.get('investigation_steps'):
        elements.append(Paragraph("Investigation Steps", heading_style))
        for i, step in enumerate(result['investigation_steps'], 1):
            elements.append(Paragraph(f"{i}. {step}", body_style))
        elements.append(Spacer(1, 0.1*inch))
    
    # Legal Sections
    if result.get('legal_sections'):
        elements.append(Paragraph("Legal Sections", heading_style))
        elements.append(Paragraph(result['legal_sections'], body_style))
        elements.append(Spacer(1, 0.1*inch))
    
    # Original Complaint
    elements.append(Paragraph("Original Complaint Text", heading_style))
    elements.append(Paragraph(complaint_text[:1000] + ("..." if len(complaint_text) > 1000 else ""), body_style))
    
    # Footer
    elements.append(Spacer(1, 0.5*inch))
    elements.append(Paragraph("This report is system-generated by CCIA v2.0.", styles['Italic']))
    
    # Build PDF
    doc.build(elements)

# Fallback if reportlab is not installed
try:
    import reportlab
except ImportError:
    print("WARNING: reportlab not installed. PDF generation will use fallback text.")
    # Fallback: create a simple text file as PDF (just rename .txt)
    def create_report_pdf(filepath, result, complaint_text):
        with open(filepath, 'w') as f:
            f.write("CCIA - Cyber Crime Report\n")
            f.write("="*40 + "\n")
            f.write(f"Case ID: {result.get('complaint_id', 'N/A')}\n")
            f.write(f"Risk: {result.get('risk_level', 'N/A')}\n")
            f.write(f"Category: {result.get('crime_category', 'N/A')}\n\n")
            f.write("Summary:\n" + result.get('case_summary', '') + "\n\n")
            f.write("Priority Action:\n" + result.get('priority_action', '') + "\n\n")
            f.write("Original Complaint:\n" + complaint_text + "\n")